<Project>

  <Import Project="Sdk.props" Sdk="Microsoft.DotNet.Arcade.Sdk" />

  <PropertyGroup>
    <RepositoryName>wpf</RepositoryName>
    <WindowsDesktopARM64Support>true</WindowsDesktopARM64Support>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFrameworkVersion>8.0</TargetFrameworkVersion>
  </PropertyGroup>
  <!-- Normalize $(TestWpfArcadeSdkPath) by appending a '\' to it if one is missing -->
  <PropertyGroup Condition="'$(TestWpfArcadeSdkPath)'!=''">
    <WpfArcadeSdkPath>$(TestWpfArcadeSdkPath)</WpfArcadeSdkPath>
    <WpfArcadeSdkPath Condition="!$(WpfArcadeSdkPath.EndsWith('\'))">$(TestWpfArcadeSdkPath)\</WpfArcadeSdkPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TestWpfArcadeSdkPath)'=='' And Exists('$(MSBuildThisFileDirectory)eng\WpfArcadeSdk\')">
    <WpfArcadeSdkPath>$(MSBuildThisFileDirectory)eng\WpfArcadeSdk\</WpfArcadeSdkPath>
  </PropertyGroup>

  <!-- Select Sdk.props from test location or eng\WpfArcadeSdk\. If neither exists, then fall back to the use of one 
      obtained using MSBuild's Sdk resolver -->
  <PropertyGroup Condition="Exists('$(WpfArcadeSdkPath)')">
    <WpfArcadeSdkProps>$(WpfArcadeSdkPath)Sdk\Sdk.props</WpfArcadeSdkProps>
    <WpfArcadeSdkTargets>$(WpfArcadeSdkPath)Sdk\Sdk.targets</WpfArcadeSdkTargets>
  </PropertyGroup>

  <!--<Import Project="$(WpfArcadeSdkProps)"
          Condition="Exists('$(WpfArcadeSdkProps)') And Exists('$(WpfArcadeSdkTargets)')"/>

  <Import Sdk="Microsoft.DotNet.Arcade.Wpf.Sdk"
          Project="Sdk.props"
          Condition="!Exists('$(WpfArcadeSdkProps)') Or !Exists('$(WpfArcadeSdkTargets)')"/>-->

  <PropertyGroup>
    <WpfReferencePath>C:\lindexi\Lib\Microsoft.WindowsDesktop.App\</WpfReferencePath>
    <WpfWindowsDesktopReferencePath Condition="'$(WpfWindowsDesktopReferencePath)' == '' and Exists('$(ProgramFiles)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.6\ref\net8.0\')">$(ProgramFiles)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.6\ref\net8.0\</WpfWindowsDesktopReferencePath>
    <WpfWindowsDesktopReferencePath Condition="'$(WpfWindowsDesktopReferencePath)' == '' and Exists('$(ProgramFiles)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.26\ref\net8.0\')">$(ProgramFiles)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.26\ref\net8.0\</WpfWindowsDesktopReferencePath>
  </PropertyGroup>

  <PropertyGroup>
    <WpfSourceDir>$(MSBuildThisFileDirectory)src\Microsoft.DotNet.Wpf\src\</WpfSourceDir>
    <WpfSharedDir>$(MSBuildThisFileDirectory)src\Microsoft.DotNet.Wpf\src\Shared\</WpfSharedDir>
    <WpfCommonDir>$(MSBuildThisFileDirectory)src\Microsoft.DotNet.Wpf\src\Common\</WpfCommonDir>
    <WpfCycleBreakersDir>$(MSBuildThisFileDirectory)cycle-breakers\</WpfCycleBreakersDir>
    <WpfCodeGenDir>$(MSBuildThisFileDirectory)eng\WpfArcadeSdk\tools\</WpfCodeGenDir>
  </PropertyGroup>

  <PropertyGroup>
    <VCTargetsPath Condition="'$(VCTargetsPath)' == ''">$([MSBuild]::GetVsInstallRoot())\Common7\IDE\VC\VCTargets\</VCTargetsPath>
  </PropertyGroup>

  <!-- warning MSB4011: 无法再次导入“C:\lindexi\Code\WpfReorganize_dotnetcampus\eng\Versions.props”。可能已在“C:\Users\lindexi\.nuget\packages\microsoft.dotnet.arcade.sdk\10.0.0-beta.25411.109\tools\DefaultVersions.props (15,3)”处导入过它。这很可能是生成创作错误。将忽略此后续导入。[C:\lindexi\Code\WpfReorganize_dotnetcampus\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj] -->
  <!-- <Import Project="$(MSBuildThisFileDirectory)eng\Versions.props"/> -->

  <!-- 以下为生成多语言资源所需，详细请看 [dotnet 读 WPF 源代码 学习使用 Microsoft.DotNet.Arcade.Sdk 处理代码里的多语言 - lindexi - 博客园](https://www.cnblogs.com/lindexi/p/19198245 ) -->
  <Import Project="$(MSBuildThisFileDirectory)eng\WpfArcadeSdk\SystemResources.props"/>
</Project>
