<Project>
  <PropertyGroup>
    <_WpfStrongNameProjectName Condition="!$(MSBuildProjectName.EndsWith('_wpftmp'))">$(MSBuildProjectName)</_WpfStrongNameProjectName>
    <_WpfStrongNameProjectName Condition="$(MSBuildProjectName.EndsWith('_wpftmp'))">$(MSBuildProjectName.SubString(0, $(MSBuildProjectName.IndexOf('_'))))</_WpfStrongNameProjectName>
    <_WpfEcmaStrongNameProjects>
      System.Xaml;
      System.Xaml-ref;
      System.Windows.Input.Manipulations;
      System.Windows.Input.Manipulations-ref;
      System.Windows.Controls.Ribbon;
      System.Windows.Controls.Ribbon-ref;
      System.Windows.Presentation;
      System.Windows.Presentation-ref;
      PresentationUI-ref;
    </_WpfEcmaStrongNameProjects>
    <StrongNameKeyId Condition="$(_WpfEcmaStrongNameProjects.Contains('$(_WpfStrongNameProjectName);'))">ECMA</StrongNameKeyId>
  </PropertyGroup>
</Project>
