<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WpfRuntime.Windows.Primitives</AssemblyName>
    <PackageId>WpfRuntime.Windows.Primitives-ref</PackageId>
    <TargetOutputRelPath>$(TargetGroup)-$(PackageId)/</TargetOutputRelPath>
    <Platforms>AnyCPU</Platforms>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(WpfSharedDir)RefAssemblyAttrs.cs" />
    <Compile Include="$(WpfSharedDir)ref\AttributesForReferenceAssemblies.cs" />
  </ItemGroup>
</Project>